language: c
sudo: false
before_install:
    - "sudo apt-get install python3 lua5.2 liblua5.2-dev lua-bitop ia32-libs"
install:
    - "git clone https://github.com/felix-lang/fbuild.git"
    - "git clone https://github.com/kirbyfan64/libcut.git"
script:
    - "fbuild/fbuild-light --cflag=-Ilibcut || cat build/fbuild.log && build/tst"
    - "fbuild/fbuild-light --clean"
    - "fbuild/fbuild-light --cflag=-Ilibcut --cflag=-m32 || cat build/fbuild.log && build/tst"
