language: c
install:
    - "git clone https://github.com/felix-lang/fbuild.git"
    - "git clone https://github.com/kirbyfan64/libcut.git"
    - "git clone https://github.com/LuaDist/luabitop.git"
    - "cd luabitop && make CFLAGS=`pkg-config --cflags lua5.2` && cd .."
script:
    - "fbuild/fbuild-light --cflag=-Ilibcut && build/tst"
    - "fbuild/fbuild-light --configure --cflag=-Ilibcut --cflag=-m32 && build/tst"
addons:
    apt:
        packages:
            - python3
            - lua5.2
            - liblua5.2-dev
env:
    - "LUA_CPATH=$TRAVIS_BUILD_DIR/luabitop/?.so"
